# Generated by Django 5.2 on 2025-07-29 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('islogin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='メッセージ')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mychat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mychat.user')),
            ],
        ),
    ]
